# Site settings
title: The Green Vintage
email: info@thegreenvintage.com
locale: en
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.thegreenvintage.com" # the base hostname & protocol for your site
cdn: '' # cdn.thegreenvintage.com
exclude: [Gemfile, Gemfile.lock, vendor]

permalink: /es/blog/:year/:month/:day/:title.html

locales:
  en: en_GB
  es: es_ES
  ca: ca_ES

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - uglifier
