# Site settings
title: The Green Vintage
email: info@thegreenvintage.com
locale: en
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.thegreenvintage.com" # the base hostname & protocol for your site
cdn: '' # cdn.thegreenvintage.com
exclude: [Gemfile, Gemfile.lock, vendor]

locales:
  en: en_GB
  es: es_ES
  ca: ca_ES

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - uglifier
