# Site settings
title: The Green Vintage
email: info@thegreenvintage.com
locale: en
description: The Green Vintage is a team of professionals specialized in the management and organization of any type of event. The company was founded with the desire to assess and plan the small moments of life and make them special.
keywords: barcelona maresme events eventos esdeveniments services servicios serveis bodas bodes weddings corporative corporativos corporatius catalunya cataluña
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.thegreenvintage.com" # the base hostname & protocol for your site
cdn: '' # cdn.thegreenvintage.com
exclude: [Gemfile, Gemfile.lock, vendor]

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

remotes:
  kakas: 'https://docs.google.com/spreadsheets/d/1-GIdfYjDpeus6tXuPDBKBN1YZAgcYJpN1fsX4H7UVL0/pub?gid=0&single=true&output=csv'
  kakos: 'https://docs.google.com/spreadsheets/d/1-GIdfYjDpeus6tXuPDBKBN1YZAgcYJpN1fsX4H7UVL0/pub?gid=0&single=true&output=csv'
