[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com https://maps.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' https://www.google-analytics.com https://maps.googleapis.com https://maps.gstatic.com https://csi.gstatic.com https://www.datocms-assets.com; object-src 'none'; default-src 'self'; frame-src https://www.youtube.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; connect-src 'self'; child-src https://www.youtube.com; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://cdnjs.cloudflare.com;"
